language: generic
sudo: required
services:
  - docker

env:
  global:
    - DOCKERBUILDER=greenaddress/ci
    - DOCKERHASH=ea10726450240149b5b25ec42e7a8fd91535f65cdb0a406502289c92cd854e8a
    - COMPILER=gcc
  matrix:
    - UNUSED=true
    - COMPILER=clang
    - DOCKERBUILDER=greenaddress/fedora_ci DOCKERHASH=79537c560edf1753bff728c5b19ad35057452e275e879c23e1cc150362bac850
    - DOCKERBUILDER=greenaddress/fedora_ci DOCKERHASH=79537c560edf1753bff728c5b19ad35057452e275e879c23e1cc150362bac850 COMPILER=clang


script:
  - docker run -v $PWD:/gdk $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "cd /gdk && ./tools/build.sh --$COMPILER"
